### PR TITLE
publish 0.1.0 with changelog

### PR DESCRIPTION
**Pull request by JoeChapman**

### CODE REVIEW

**Comment by easternbloc** [comment]
lol better.

**Review by sulthan-ahmed — COMMENTED** [review]
LGTM the only question I have is why do we have @JoeChapman against it? can we not tell from the commit who it came from?

**Comment by easternbloc** [comment]
we put a name next to it of who published it @sulthan-ahmed

**Comment by easternbloc** [comment]
it's just a friendly thing but you're absolutely right

**Comment by easternbloc** [comment]
we can really only deduce who commited from the commit message the name convention on the release notes is more who published it to npm

**Comment by sulthan-ahmed** [comment]
👍

**Pull request merged**
